export enum Type {
	ADDRESS_TYPE = '/address',
	AIRPORT_TYPE = '/air/port',
	COLLECTION_REF_TYPE = '/api/refs/collection',
	API_ERROR_TYPE = '/api/error',
	OBJECT_REF_TYPE = '/api/refs/object',
	API_RESPONSE_TYPE = '/api/response',
	BOOKING_TYPE = '/booking',
	COMMERCIAL_INVOICE_TYPE = '/commercial_invoice',
	CUSTOMS_ENTRY_TYPE = '/customs_entry',
	DOCUMENT_TYPE = '/document',
	PAGE_TYPE = '/api/collections/paginated',
	PLACE_TYPE = '/place',
	QUANTITY_WEIGHT_TYPE = '/quantity/weight',
	QUANTITY_VOLUME_TYPE = '/quantity/volume',
	RAILPORT_TYPE = '/ocean/railport',
	ROADPORT_TYPE = '/trucking/port',
	SEAPORT_TYPE = '/ocean/port',
	SHIPMENT_TYPE = '/shipment',
	SHIPMENT_LEG_TYPE = '/shipment_leg',
	SHIPMENT_NODE_TYPE = '/shipment_node',
	TERMINAL_TYPE = '/shipment_node/terminal',
}
