export enum Type {
	Address = '/address',
	Airport = '/air/port',
	CollectionRef = '/api/refs/collection',
	ApiError = '/api/error',
	ObjectRef = '/api/refs/object',
	ApiResponse = '/api/response',
	Booking = '/booking',
	CommercialInvoice = '/commercial_invoice',
	CustomsEntry = '/customs_entry',
	Document = '/document',
	Page = '/api/collections/paginated',
	Place = '/place',
	Weight = '/quantity/weight',
	Volume = '/quantity/volume',
	Railport = '/ocean/railport',
	Roadport = '/trucking/port',
	Seaport = '/ocean/port',
	Shipment = '/shipment',
	ShipmentLeg = '/shipment_leg',
	ShipmentNode = '/shipment_node',
	Terminal = '/shipment_node/terminal',
}
